config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root 'posts#index'
  get 'dashboard', to: 'posts#dashboard'
  get '/admin', to: 'admin/users#index'

  devise_scope :user do
    get '/users/two_factor/confirm' => 'users/registrations#confirm_two_factor',
      as: :confirm_two_factor

    put '/users/two_factor' => 'users/registrations#confirm_two_factor_update',
      as: :confirm_two_factor_update

  end

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users, only: %i[show]

  resources :posts do
    get '/top/posts',  controller: 'posts', action: 'top', on: :collection
    collection do
      get :status
    end
    resources :comments
    resources :likes
    resources :rates, only: :create
  end

  resources :categories do
    resources :posts
  end

  namespace :admin do
    resources :users, :posts, :categories
  end
end

app/views/shared/_admin_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-custom navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse"><span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span></button>
				<a class="navbar-brand" href="<%= root_path %>"><span>Golden</span>Blog</a>
		</div>
	</div><!-- /.container-fluid -->
</nav>

app/views/shared/_admin_sidebar.html.erb
<div id="sidebar-collapse" class="sidebar">
	<div class="profile-sidebar">

		<div class="profile-userpic">
			<img src="<%= current_user.avatar %>" class="img-responsive" alt="">
		</div>

		<div class="profile-usertitle">
			<div class="profile-usertitle-name"><%= current_user.email %></div>
			<div class="profile-usertitle-status"><span class="indicator label-success"></span>Online</div>
			<div><%= link_to 'Edit profile', edit_user_registration_path %></div>
		</div>

		<div class="clear"></div>
	</div>

	<div class="divider"></div>

	<form role="search">
		<div class="form-group">
			<input type="text" class="form-control" placeholder="Search">
		</div>
	</form>

	<ul class="nav menu">
		<li>
			<a href="<%= admin_users_path %>"><em class="fa fa-dashboard">&nbsp;</em> Users Management</a>
		</li>

		<li>
			<a href="<%= admin_posts_path %>"><em class="fa fa-bar-chart">&nbsp;</em> Posts Status </a>
		</li>

		<li>
			<a href="<%= admin_categories_path %>"><em class="fa fa-toggle-off">&nbsp;</em> Categories </a>
		</li>

		<ul class="children collapse" id="sub-item-1">
			<li>
				<a class="" href="#"><span class="fa fa-arrow-right">&nbsp;</span> Sub Item 1</a>
			</li>

			<li>
				<a class="" href="#"><span class="fa fa-arrow-right">&nbsp;</span> Sub Item 2</a>
			</li>

			<li>
				<a class="" href="#"><span class="fa fa-arrow-right">&nbsp;</span> Sub Item 3</a>
			</li>
		</ul>

		<li><%= link_to "Logout", destroy_user_session_url, method: :delete %></li>
	</ul>
</div><!--/.sidebar-->

app/views/shared/_form.html.erb
<div class="row">
  <div class="col-12">
    <%= form_with(model: @post, data: { remote: false}) do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: 'edit-post' %>
      </div>
      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image %>
        <% if f.object.image.url.present? %>
          <%= image_tag f.object.image.url, class: 'img-thumbnail', width: '200px'%>
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label :category , "Category" %>
        <%= f.collection_select :category_id, @categories, :id, :name, prompt: "Select Category" %>
      </div>

      <% if current_user&.admin? %>
        <div class="form-group">
          <%= f.label :status , "Status" %>
          <%= select_tag 'post[status]', options_for_select(Post::STATUSES.inject({}) { |obj, item| obj.merge(item[1] => item[0].to_s) }) %>
        </div>
      <% end %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/shared/_guest_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-custom navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-collapse" aria-expanded="true">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href=<%= root_path %>>Golden<span>Blog</span></a>

			<div class="collapse navbar-collapse sayhi" id="menu-collapse">
				<ul class="nav navbar-nav ml-auto" style="background: #222222;">
					<li class="nav-item">
						<a class="nav-link marg" href=<%= new_user_session_path %>>Sign in</a>
					</li>
					<li class="nav-item">
						<a class="nav-link marg" href=<%= new_user_registration_path %>>Sign up</a>
					</li>
					<li class="nav-item">
						<a class="nav-link marg" href=<%= user_facebook_omniauth_authorize_path %>>Sign in with Facebook</a>
					</li>
				</ul>
			</div>

		</div>
	</div><!-- /.container-fluid -->
</nav>

<!------------------------------------------------------------>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-custom navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-collapse" aria-expanded="true">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href=<%= root_path %>>Golden<span>Blog</span></a>

			<div class="collapse navbar-collapse sayhi" id="menu-collapse">
				<ul class="nav navbar-nav ml-auto" style="background: #222222;">
					<li class="nav-item">
						<a class="nav-link marg" href=<%= new_post_path %>>Add New Post</a>
					</li>
					<li class="nav-item">
						<a class="nav-link marg" href=<%= top_posts_posts_path %>>Top Posts</a>
					</li>
					<li class="nav-item">
						<a class="nav-link marg" href=<%= categories_path %>>Category</a>
					</li>
					<li class="nav-item">
						<a class="nav-link marg" href=<%= status_posts_path %>>Posts Status</a>
					</li>
					<li class="nav-item">
						<%= link_to "Edit profile", edit_user_registration_path, class: 'marg' %>
          </li>
					<li class="nav-item">
						<%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'marg' %>
					</li>
				</ul>
			</div>

		</div>
	</div><!-- /.container-fluid -->
</nav>

<!------------------------------------------------------------>

app/views/shared/_notice.html.erb
<% if notice %>
  <p class="alert alert-success" style="text-align: center"><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert alert-danger" style="text-align: center"><%= alert %></p>
<% end %>

app/views/shared/_post_show.html.erb
<% posts.each do |post| %>
  <div class="post-preview">
    <a href=<%= post_path(post.id) %>>
      <h2 class="post-title"><strong><%= post.title.titleize %></strong></h2>
      <h3 class="post-subtitle">Problems look mighty small from 150 miles up</h3>
    </a>

    <p class="post-meta">Posted by
      <a href=<%= user_path(post.user.id) %>><%= post.user.email %></a>
      on <%= post.created_at %><br>

      <% if request.path == '/posts/top/posts' %>
        <strong><%= post.likes.count %> <%= post.likes.count == 1 ? 'like' : post.likes.count == 0 ? 'like' : 'likes' %></strong>
      <% elsif request.path == '/posts/status'%>
        <strong>Status: <%= post.status == 'New' ? 'Pending' : post.status %></strong>
      <% end %>
    </p>

      <% if current_user&.role == 'admin' || post.user == current_user %>
        <%= link_to 'Edit post', edit_post_path(post), class: 'btn btn-primary' %>
        <%= link_to 'Destroy', post_path(post.id), method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete this post?"}, remote: true %>
      <% end %>

      <hr>
  </div>
<% end %>