config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root 'posts#index'
  get 'dashboard', to: 'posts#dashboard'
  get '/admin', to: 'admin/users#index'

  devise_scope :user do
    get '/users/two_factor/confirm' => 'users/registrations#confirm_two_factor',
      as: :confirm_two_factor

    put '/users/two_factor' => 'users/registrations#confirm_two_factor_update',
      as: :confirm_two_factor_update

  end

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users, only: %i[show]

  resources :posts do
    get '/top/posts',  controller: 'posts', action: 'top', on: :collection
    collection do
      get :status
    end
    resources :comments
    resources :likes
    resources :rates, only: :create
  end

  resources :categories do
    resources :posts
  end

  namespace :admin do
    resources :users, :posts, :categories
  end
end

app/models/post.rb
class Post < ApplicationRecord
  STATUSES = {
    Approved: 'Approved',
    Declined: 'Declined',
    New: 'New'
  }.freeze

  belongs_to :user
  belongs_to :category
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :user_rated, through: :rates

  mount_uploader :image, ImageUploader
  validates :title, :content, presence: true
  validate :check_status

  scope :approved, -> { where(status: 'Approved') }

  def self.search(search)
    category_id = Category.find_by('lower(name) = ?', search.downcase)
    @posts = Post.approved
    @posts = if category_id.present?
               @posts.where(category_id: category_id)
             else
               @posts.where('title LIKE ?', "%#{search}%")
             end
  end

  def rating_point(user)
    rates.find_by(user_id: user.id)&.value
  end

  def check_status
    if Post::STATUSES[status.to_sym].nil?
      errors.add(:status, 'invalid')
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_action :prepare_post, only: %i[edit update show destroy]

  def index
    @new_posts = prepare_status_posts('New')
    @approved_posts = prepare_status_posts('Approved')
    @declined_posts = prepare_status_posts('Declined')
  end

  def edit
    @categories = Category.all
  end

  def update
    @post.update(post_params)
  end

  def show
    redirect_to post_path(@post)
  end

  def destroy
    @post.destroy

    flash[:notice] = 'Post was successfully destroyed.'
    redirect_back(fallback_location: admin_posts_path)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def prepare_post
    @post = Post.find(params[:id])
  end

  def prepare_status_posts(status)
    Post.where(status: status).order('created_at')
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :prepare_approved_posts, only: %i[index top]
  before_action :prepare_post, only: %i[edit update destroy]
  before_action :prepare_categories, only: %i[new edit]

  def index
    @posts = Post.search(params[:search]) if params[:search].present?

    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post), notice: 'Post was successfully created.'
    else
      prepare_categories
      flash[:alert] = @post.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: 'Post was successfully updated.'
    else
      prepare_categories
      flash[:alert] = @post.errors.full_messages.join(', ')
      render :edit
    end
  end

  def show
    @post = Post.find_by(id: params[:id])

    @rating_point = @post.rating_point(current_user) || 0
    @pre_like = @post.likes.find { |like| like.user_id == current_user.id }
  end

  def destroy
    @post.destroy

    flash[:notice] = 'Post was successfully destroyed.'
    redirect_back(fallback_location: root_path)
  end

  def top
    @posts = if params[:choice] == 'Today'
               @posts.where('created_at BETWEEN ? AND ?', Time.now.beginning_of_day, Time.now)
             elsif params[:choice] == 'Week'
               @posts.where('created_at BETWEEN ? AND ?', Time.now.beginning_of_week, Time.now.end_of_week)
             elsif params[:choice] == 'Month'
               @posts.where('created_at BETWEEN ? AND ?', Time.now.beginning_of_month, Time.now.end_of_month)
             else
               Post.none
             end.sort_by { |post| -post.likes.count }.first 3

    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  def status
    @posts = current_user.posts
  end

  private

  def post_params
    params[:status] ||= "New"
    params.require(:post).permit(:title, :content, :image, :category_id, :status)
  end

  def prepare_post
    @post = if current_user.admin?
              Post.find(params[:id])
            else
              current_user.posts.find(params[:id])
            end
  end

  def prepare_categories
    @categories = Category.all
  end

  def prepare_approved_posts
    @posts = Post.approved
  end
end

app/views/admin/posts/_posts.html.erb
<div class="panel panel-container">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Author</th>
            <th>Post Title</th>
            <th colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% posts.each do |post| %>
            <tr>
              <td><%= post.user.email %></td>
              <td><%= post.title %></td>
              <td><%= link_to 'Show post content', admin_post_path(post.id), class: 'btn btn-warning' %></td>
              <% if post.status == 'New' %>
                <td><%= button_to "Approve", post_path(post.id), method: :patch, params: { post: { status: 'Approved' } }, class: 'btn btn-primary'%></td>
                <td><%= button_to "Decline", post_path(post.id), method: :patch, params: { post: {status: 'Declined' } }, class: 'btn btn-danger'%></td>
              <% else %>
                <td><%= link_to 'Edit post', edit_admin_post_path(post.id), class: 'btn btn-primary' %></td>
                <td><%= link_to 'Delete post', admin_post_path(post.id), method: :delete, data: { confirm: 'Are you sure you want to delete this user?' }, class: 'btn btn-danger', remote: true %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
		</div>

app/views/admin/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'shared/form' %>
<br>

app/views/admin/posts/index.html.erb
<div class="main">
	<div class="row">
		<ol class="breadcrumb">
			<li><a href="#">
				<em class="fa fa-home"></em>
			</a></li>
			<li class="active">Posts Status </li>
		</ol>
	</div><!--/.row-->

	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">Pending Posts</h1>
		</div>
	</div><!--/.row-->
	<%= render 'posts', posts: @new_posts %>

	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">Approved Posts</h1>
		</div>
	</div><!--/.row-->
	<%= render 'posts', posts: @approved_posts %>


	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">Declined Posts</h1>
		</div>
	</div><!--/.row-->
	<%= render 'posts', posts: @declined_posts %>
</div>