config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root 'posts#index'
  get 'dashboard', to: 'posts#dashboard'
  get '/admin', to: 'admin/users#index'

  devise_scope :user do
    get '/users/two_factor/confirm' => 'users/registrations#confirm_two_factor',
      as: :confirm_two_factor

    put '/users/two_factor' => 'users/registrations#confirm_two_factor_update',
      as: :confirm_two_factor_update

  end

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users, only: %i[show]

  resources :posts do
    get '/top/posts',  controller: 'posts', action: 'top', on: :collection
    collection do
      get :status
    end
    resources :comments
    resources :likes
    resources :rates, only: :create
  end

  resources :categories do
    resources :posts
  end

  namespace :admin do
    resources :users, :posts, :categories
  end
end

app/models/post.rb
class Post < ApplicationRecord
  STATUSES = {
    Approved: 'Approved',
    Declined: 'Declined',
    New: 'New'
  }.freeze

  belongs_to :user
  belongs_to :category
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :user_rated, through: :rates

  mount_uploader :image, ImageUploader
  validates :title, :content, presence: true
  validate :check_status

  scope :approved, -> { where(status: 'Approved') }

  def self.search(search)
    category_id = Category.find_by('lower(name) = ?', search.downcase)
    @posts = Post.approved
    @posts = if category_id.present?
               @posts.where(category_id: category_id)
             else
               @posts.where('title LIKE ?', "%#{search}%")
             end
  end

  def rating_point(user)
    rates.find_by(user_id: user.id)&.value
  end

  def check_status
    if Post::STATUSES[status.to_sym].nil?
      errors.add(:status, 'invalid')
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_action :prepare_post, only: %i[edit update show destroy]

  def index
    @new_posts = prepare_status_posts('New')
    @approved_posts = prepare_status_posts('Approved')
    @declined_posts = prepare_status_posts('Declined')
  end

  def edit
    @categories = Category.all
  end

  def update
    @post.update(post_params)
  end

  def show
    redirect_to post_path(@post)
  end

  def destroy
    @post.destroy

    flash[:notice] = 'Post was successfully destroyed.'
    redirect_back(fallback_location: admin_posts_path)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def prepare_post
    @post = Post.find(params[:id])
  end

  def prepare_status_posts(status)
    Post.where(status: status).order('created_at')
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :prepare_approved_posts, only: %i[index top]
  before_action :prepare_post, only: %i[edit update destroy]
  before_action :prepare_categories, only: %i[new edit]

  def index
    @posts = Post.search(params[:search]) if params[:search].present?

    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post), notice: 'Post was successfully created.'
    else
      prepare_categories
      flash[:alert] = @post.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: 'Post was successfully updated.'
    else
      prepare_categories
      flash[:alert] = @post.errors.full_messages.join(', ')
      render :edit
    end
  end

  def show
    @post = Post.find_by(id: params[:id])

    @rating_point = @post.rating_point(current_user) || 0
    @pre_like = @post.likes.find { |like| like.user_id == current_user.id }
  end

  def destroy
    @post.destroy

    flash[:notice] = 'Post was successfully destroyed.'
    redirect_back(fallback_location: root_path)
  end

  def top
    @posts = if params[:choice] == 'Today'
               @posts.where('created_at BETWEEN ? AND ?', Time.now.beginning_of_day, Time.now)
             elsif params[:choice] == 'Week'
               @posts.where('created_at BETWEEN ? AND ?', Time.now.beginning_of_week, Time.now.end_of_week)
             elsif params[:choice] == 'Month'
               @posts.where('created_at BETWEEN ? AND ?', Time.now.beginning_of_month, Time.now.end_of_month)
             else
               Post.none
             end.sort_by { |post| -post.likes.count }.first 3

    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  def status
    @posts = current_user.posts
  end

  private

  def post_params
    params[:status] ||= "New"
    params.require(:post).permit(:title, :content, :image, :category_id, :status)
  end

  def prepare_post
    @post = if current_user.admin?
              Post.find(params[:id])
            else
              current_user.posts.find(params[:id])
            end
  end

  def prepare_categories
    @categories = Category.all
  end

  def prepare_approved_posts
    @posts = Post.approved
  end
end

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>Edit Post</h1>
      <%= render "shared/form" %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<header class="masthead" style="background-image: url('../../assets/img/home-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="blog-heading">
          <h1>GoldenBlog</h1>
          <span class="subheading">A Practice Blog by Mabel</span>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <h3>Search posts:</h3>
      <p>
        <%= form_tag(posts_path, method: 'get', remote: true) %>
        <%= text_field_tag(:search) %>
        <%= submit_tag("Search")%>
      </p>

      <div class="search-field">
        <%= render 'shared/post_show', posts: @posts %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.js.erb
jQuery('.search-field').html('').append("<%= escape_javascript render(partial: 'shared/post_show', locals: { posts: @posts }) %>")

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>New Post</h1>
      <%= render "shared/form" %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% set_meta_tags og: { title: 'GoldenBlog' } %>
<% set_meta_tags og: { description: @post.title } %>
<% set_meta_tags og: { image: @post.image } %>

<div class="post">

  <!-- Page Header -->
  <header class="masthead">
  <div class="overlay"></div>
  <div class="container">
    <div class="col-lg-8 col-md-10 mx-auto">
      <div class="post-heading">
        <h1><strong><%= @post.title.titleize %></strong><h1>
        <span class="meta">Posted by <a href=<%= admin_user_path(@post.user.id) %>><%= @post.user.email %></a> on <%= @post.created_at %></span>
      </div>
    </div>
  </div>
  </header>

  <!-- Post Content -->
  <div>
    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <p><%= @post.content.html_safe %></p>

            <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>

            <% if @post.image.present? %>
              <p><%= image_tag(@post.image.standard.url) %></p>
            <% end %>

            <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>

            <% if current_user %>
              <p>Post Rating </p>
              <p class='points'>Points: <%= post_rate(@post) %>/5</p>
              <form name='post_rating' id="post_rating_form_<%= @post.id %>" method='post' action="<%= post_rates_path(@post) %>">
                <div class="rating">
                  <% 5.downto(1).each do |i| %>
                    <input type="radio" name="rating" value="<%= i %>" id="rating_<%= i %>_post_<%= @post.id %>" <%= i == @rating_point ? 'checked' : '' %>>
                    <label for="rating_<%= i %>_post_<%= @post.id %>">☆</label>
                  <% end %>
                </div>
              </form>

              <p class="like_show"><strong><%= @post.likes.count == 0 ? 'Like: ' : @post.likes.count == 1 ? 'Like: ' : 'Likes: ' %></strong><%= @post.likes.count %></p>

              <div class="like-container">
                <% if @pre_like %>
                  <%= button_to 'Dislike', post_like_path(@post, @pre_like), method: :delete, remote: true, class: "btn btn-primary" %>
                <% else %>
                  <%= button_to 'Like', post_likes_path(@post), method: :post, remote: true, class: "btn btn-primary" %>
                <% end %>
              </div>
              <br>

              <p>
                <strong>Comments: </strong><br>
                <% @post.comments.each do |comment|%>
                  <%= comment.user.email %>:
                  <%= comment.content %>
                  <br>
                <% end %>
              </p>
              <br>

              <%= form_with(model: [@post, Comment.new] ) do |f| %>
                <%= f.label :comment %>
                <br>
                <%= f.text_field :content %>
                <br><br>

                <%= f.submit "Add comment", class: "btn btn-primary" %>
              <% end %>
              <br>
            <% end %>
            <hr>

            <!-- Go to www.addthis.com/dashboard to customize your tools -->
            <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5ef3002f1be84787"></script>

            <!-- Go to www.addthis.com/dashboard to customize your tools -->
            <div class="addthis_inline_share_toolbox"></div>

          </div>
        </div>
      </div>
    </article>
  </div>
</div>

app/views/posts/status.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <h1>All Posts Status</h1>
      <%= render 'shared/post_show', posts: @posts %>
    </div>
  </div>
</div>

app/views/posts/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <h1>Top Posts</h1>
      <p>
        <%= form_tag(top_posts_posts_path, method: :get, class: 'show_top') %>
        <%= select_tag "choice", options_for_select(["Select a time", "Today", "Week", "Month"], params[:choice]) %>
      </p>

      <%= render 'shared/post_show', posts: @posts %>
    </div>
  </div>
</div>

app/views/posts/top.js.erb
jQuery('.table-posts tbody').html('').append("<%= escape_javascript render(partial: 'posts/post_show', locals: { :posts => @posts }) %>")