config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root 'posts#index'
  get 'dashboard', to: 'posts#dashboard'
  get '/admin', to: 'admin/users#index'

  devise_scope :user do
    get '/users/two_factor/confirm' => 'users/registrations#confirm_two_factor',
      as: :confirm_two_factor

    put '/users/two_factor' => 'users/registrations#confirm_two_factor_update',
      as: :confirm_two_factor_update

  end

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users, only: %i[show]

  resources :posts do
    get '/top/posts',  controller: 'posts', action: 'top', on: :collection
    collection do
      get :status
    end
    resources :comments
    resources :likes
    resources :rates, only: :create
  end

  resources :categories do
    resources :posts
  end

  namespace :admin do
    resources :users, :posts, :categories
  end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def create
    @category = current_user.categories.new(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      redirect_to categories_path, alert: 'Category cannot be null or it maybe already exists.'
    end
  end

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts.approved
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end

end

app/views/categories/index.html.erb
<h1>All Categories</h1>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Category Name</th>
      <th>Category Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category|%>
    <tr>
      <td><%= category.name %></td>
      <td><%= category.description.html_safe %></td>
      <td><%= link_to "Show posts", category_path(category), class: 'btn btn-warning' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= form_with(model: [@user, Category.new]) do |f| %>
<p>
  <%= f.label :name, "New Category Name" %><br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :description, "Category Description" %><br>
  <%= f.text_area :description %>
</p>

<%= f.submit "Add category" %>
<% end %>

<br>

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <h1>Category: <%= @category.name.upcase() %></h1>
      <h3>Description: <%= @category.description.html_safe %></h3>
      <%= link_to "Add new #{@category.name} post", new_category_post_path(@category), class:"btn btn-primary" %>
      <br><br>

      <%= render 'shared/post_show', posts: @posts %>
    </div>
  </div>
</div>